#!/usr/bin/env sh

sync_run() {

    if $(hasFlag obsidian); then
	local OB_PATH="/Users/sophronios/PARA/RESOURCES/Obsidian_Vault"

	cd "$OB_PATH"

	have_connection=$(ping -c 1 "1.1.1.1" >/dev/null 2>&1  && echo true || echo false)

	[[ $have_connection == true ]] && git pull >/dev/null 2>&1

	if [ -n "$(git status --porcelain)" ] ; then
	    git add . >> /Users/sophronios/LOGS
	    git commit -q -m "Last Sync: $(date +"%Y-%m-%d %H:%M:%S")" >> /Users/sophronios/LOGS
	    [[ $have_connection == true ]] && git push -q >> /Users/sophronios/LOGS
	fi
    fi
}
