#!/usr/bin/env sh

sync_run() {

    if $(hasFlag obsidian); then
	local OB_PATH="/Users/sophronios/PARA/RESOURCES/Obsidian_Vault"

	cd "$OB_PATH"

	#have_connection=$(ping q -c 1 "1.1.1.1"   && echo true || echo false) #>/dev/null 2>&1

	$(hasInternet) && git pull #>/dev/null 2>&1
	#git pull

	if [ -n "$(git status --porcelain)" ] ; then
	    git add . >> /Users/sophronios/LOGS
	    git commit -q -m "Last Sync: $(date +"%Y-%m-%d %H:%M:%S")" >> /Users/sophronios/LOGS
	    $(hasInternet) && git push -q #>> /Users/sophronios/LOGS
	fi
	exit 0
    fi
    
    echo "Invalid option"
    sync_help
}

sync_help() {
   cat - <<EOF 

Description:
       uses github to sycronize Obsidian vault.

Usage: 
       please sync obsidian

EOF

}
